# ServiceAccount for the SPIFFE CSI driver
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spiffe-csi-driver
  namespace: spire
---
# DaemonSet to run the SPIFFE CSI driver on each node
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spiffe-csi-driver
  namespace: spire
  labels:
    app: spiffe-csi-driver
spec:
  selector:
    matchLabels:
      app: spiffe-csi-driver
  template:
    metadata:
      namespace: spire
      labels:
        app: spiffe-csi-driver
    spec:
      serviceAccountName: spiffe-csi-driver
      containers:
        - name: spiffe-csi-driver
          image: ghcr.io/spiffe/spiffe-csi-driver:nightly
          imagePullPolicy: IfNotPresent
          args: [
            "-workload-api-socket-dir", "/run/spire/sockets",
            "-csi-socket-path", "/spiffe-csi/csi.sock",
          ]
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /run/spire/sockets
              name: spire-agent-socket
              readOnly: true
            - mountPath: /spiffe-csi
              name: spiffe-csi-socket
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
            privileged: true
        - name: node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.6.0
          imagePullPolicy: IfNotPresent
          args: [
            "-csi-address", "/spiffe-csi/csi.sock",
            "-kubelet-registration-path", "/var/lib/kubelet/plugins/csi.spiffe.io/csi.sock",
          ]
          volumeMounts:
            - mountPath: /spiffe-csi
              name: spiffe-csi-socket
            - name: kubelet-plugin-registration
              mountPath: /registration
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: spiffe-csi-socket
          hostPath:
            path: /var/lib/kubelet/plugins/csi.spiffe.io
            type: DirectoryOrCreate
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: kubelet-plugin-registration
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
---
# CSIDriver configuration
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: "csi.spiffe.io"
spec:
  attachRequired: false
  podInfoOnMount: true
  fsGroupPolicy: None
  volumeLifecycleModes:
    - Ephemeral
